package empresaTelefonia;

public enum OpcionesMenu {
    CREAR_CUENTA,
    BORRAR_CUENTA,
    CAMBIAR_TARIFA,
    MOSTRAR_DATOS_CLIENTE,
    MOSTRAR_CLIENTES,
    DAR_ALTA_LLAMADA,
    MOSTRAR_LLAMADAS_CLIENTE,
    EMITIR_FACTURA,
    MOSTRAR_DATOS_FACTURA,
    MOSTRAR_FACTURAS_CLIENTE;
}
